require('./curry')
require('./compose')
require('./pipe')
require('./flip')
require('./unary')
require('./memoize')
require('./addIndex')
require('./apply')
require('./partial')
require('./__')
require('./invoker')
require('./nthArg')
require('./once')

require('./identity')
require('./tap')
require('./always')
require('./t')
require('./f')

require('./and')
require('./or')
require('./not')

require('./when')
require('./unless')
require('./until')
require('./cond')

require('./all')
require('./any')
require('./none')
require('./passAll')
require('./passAny')
require('./passNone')

require('./type')
require('./isNil')
require('./isNaN')
require('./isEmpty')
require('./is')

require('./path')
require('./property')
require('./keys')
require('./keysIn')
require('./values')
require('./valuesIn')

require('./clone')
require('./pick')
require('./pickBy')
require('./omit')
require('./omitBy')
require('./has')
require('./hasIn')
require('./where')

require('./add')
require('./subtract')
require('./multiply')
require('./divide')
require('./modulo')
require('./inc')
require('./dec')
require('./floor')
require('./ceil')
require('./round')
require('./max')
require('./min')
require('./sum')
require('./sumBy')

require('./gt')
require('./gte')
require('./lt')
require('./lte')
require('./eq')
require('./equals')

require('./map')
require('./reduce')
require('./filter')
require('./reject')
require('./find')
require('./findIndex')
require('./forEach')
require('./forOwn')
require('./forIn')
require('./times')

require('./indexOf')
require('./indexOfFrom')
require('./lastIndexOf')
require('./lastIndexOfFrom')
require('./reverse')
require('./uniq')
require('./uniqBy')
require('./uniqWith')
require('./range')
require('./includes')
require('./head')
require('./tail')
require('./last')
require('./initial')
require('./nth')
require('./size')
require('./drop')
require('./pluck')

require('./intersection')

require('./pair')
require('./fromPairs')

require('./trim')
require('./capitalize')
require('./camelCase')
require('./repeat')
require('./endsWith')
require('./startsWith')
require('./replace')
require('./split')
require('./splitAt')
