require('./curry')
require('./compose')
require('./pipe')
require('./flip')
require('./unary')
require('./memoize')
require('./addIndex')
require('./apply')

require('./identity')
require('./tap')
require('./always')
require('./t')
require('./f')

require('./and')
require('./or')
require('./not')

require('./when')
require('./unless')
require('./until')
require('./cond')

require('./all')
require('./any')
require('./none')
require('./passAll')
require('./passAny')
require('./passNone')

require('./type')
require('./isNil')
require('./isNaN')
require('./isEmpty')
require('./is')

require('./path')

require('./intersection')
